export function launcherHtml(token: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spawn · Local testing</title><link rel="stylesheet" href="/__spawn/style.css"></head>
<body data-document-token="${token}"><header><strong>SPAWN <span>LOCAL TESTING</span></strong><div class="players" aria-label="Test player"><button data-player="alice" aria-pressed="true">Alice</button><button data-player="bob" aria-pressed="false">Bob</button><button data-player="empty" aria-pressed="false">Empty balance</button></div><button id="reopen">Reopen game</button><button id="disconnect">Disconnect</button><button id="reset">Reset testing</button></header>
<div class="notice">Fake accounts and balances. Nothing here is sent to Spawn or saved after you close this page. Test your private preview on Spawn before publishing.</div>
<main><section id="game"><div id="frame-slot"></div></section><aside><h1>Game connection</h1><p id="status" role="status">Waiting for the SDK…</p><p id="balance"></p><h2>Local transactions</h2><ol id="history"></ol><p class="hint">Request an entry payment in the game to test Confirm, Cancel and success. Use Empty balance to test rejection. Scores stay unverified and never pay rewards.</p></aside></main>
<dialog id="payment"><h2 id="payment-title">Confirm test payment</h2><p id="payment-copy">Pay 10 TEST to this local test game?</p><p class="hint">This is a simulation. No real tokens move.</p><div class="actions"><button id="cancel">Cancel</button><button id="confirm" class="primary">Confirm 10 TEST</button><button id="continue" class="primary" hidden>Continue to game</button></div></dialog>
<script type="module" src="/__spawn/host.js"></script></body></html>`;
}
export const launcherCss = `:root{font:15px/1.5 system-ui;color:#202321;background:#f5f6f3}*{box-sizing:border-box}body{margin:0}header{display:flex;flex-wrap:wrap;align-items:center;gap:14px;padding:14px 24px;background:white;border-bottom:1px solid #dadfd7}strong{margin-right:auto;letter-spacing:.02em}strong span{font-size:11px;margin-left:8px;background:#d4ff57;padding:4px 6px;border-radius:3px}button{font:inherit;padding:8px 12px;border:1px solid #cdd3c9;border-radius:6px;background:white;color:inherit;cursor:pointer}.players{display:flex;gap:4px}.players button[aria-pressed="true"]{background:#202321;color:white}button:disabled{opacity:.5;cursor:wait}.notice{padding:10px 24px;background:#ecf0e5;color:#52594e;font-size:13px}main{display:grid;grid-template-columns:minmax(0,1fr) 280px;height:calc(100vh - 130px);min-height:440px}#frame-slot,iframe,#game{height:100%;width:100%;border:0;background:#151a16}aside{padding:20px;overflow:auto;border-left:1px solid #dadfd7}h1,h2{font-size:16px;margin:0 0 14px}h2{margin-top:24px}.hint{font-size:13px;color:#67705f}ol{padding-left:20px;font-size:13px}li{padding-bottom:8px;overflow-wrap:anywhere}dialog{max-width:410px;width:calc(100% - 32px);padding:28px;border:1px solid #cdd3c9;border-radius:12px;box-shadow:0 16px 70px #0003}dialog::backdrop{background:#101a1266}.actions{display:flex;gap:12px;justify-content:flex-end;margin-top:24px}.primary{background:#d4ff57;border-color:#b4df3d;font-weight:650}.paid{color:#23834b}.paid:before{content:'✓';display:inline-grid;place-items:center;width:36px;height:36px;background:#e1f3e6;border-radius:50%;margin-right:8px;animation:appear .25s ease-out}@keyframes appear{from{transform:scale(.7);opacity:.2}}@media(prefers-reduced-motion:reduce){.paid:before{animation:none}}@media(max-width:760px){main{display:block;height:auto}#game{height:65vh}aside{border-left:0}header{padding:12px;gap:8px}}`;
